### PR TITLE
NMI clarifications added

### PR DESCRIPTION
**Pull request by Silabs-ArjanB**
Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

### CODE REVIEW

**Comment by eroom1966** [comment]
could we please add that the NMI are edge-sensitive, to distinguish from irq_* which are level-sensitive
Then I think this is fully clarified

**Comment by Silabs-ArjanB** [comment]
Hi @Silabs-ArjanB, I think using the word edge or level sensitive is a bit weird in the context of our NMIs as there are no corresponding NMI _pins_ on the core. I could describe the NMIs being triggered by certain 'load/store fault _events_', which I think then would convey the same meaning as what you might call edge sensitive.

**Comment by eroom1966** [comment]
'load/store fault events', is fine
Thx

**Comment by eroom1966** [comment]
the two issues are resolved with these changes
Thx

**Review by silabs-oysteink — APPROVED** [review]

**Pull request merged**
