### PR TITLE
Fixed dsim/vsim compatibility

### PR DESCRIPTION
**Pull request by silabs-halfdan**
Updated sim tracer to use explicit casting to avoid causing issues for some simulators.

### CODE REVIEW

**Comment by silabs-halfdan** [comment]
This is a fix for https://github.com/openhwgroup/cv32e40s/issues/148

**Comment by MikeOpenHWGroup** [comment]
Works with dsim.

**Comment by MikeOpenHWGroup** [comment]
Ah, we've got  the same issue on _both_ the E40X and E40S.  This fix also needs to be applied to the E40S.

**Comment by Silabs-ArjanB** [comment]
@MikeOpenHWGroup Yes, that was understood. The fix from the 40X will get merged into the 40S once we do the next merge cycle.

**Pull request merged**
